### PR TITLE
fix bs4 and quote issue

### LINKED ISSUE #90: BUG: Screen Does't work !!!!
### finvizfinance version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the master branch of finvizfinance.

### Reproducible Example

```python
from finvizfinance.screener.overview import Overview
foverview = Overview()
filters_dict = {'Index': 'S&P 500', 'Sector': 'Basic Materials'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view()
df.head()


Error
cgptenv/lib/python3.11/site-packages/finvizfinance/screener/overview.py", line 280, in screener_view
    rows = table.findAll("tr")
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findAll'
```

### Issue Description

the error is because table with class name  "table-light" does not exist on dark mode

table = soup.find("table", class_="table-light")

### Expected Behavior

return a list of tickers

### Installed Versions

<details>

Replace this line with the output of finvizfinance.__version__

finvizfinance-0.14.6

</details>

### PR DESCRIPTION
**Pull request by lit26**
## Description

Fix #90 #92 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code styling or code optimize

### CODE REVIEW

**Comment by Mytak** [comment]
The current commit [87](https://github.com/lit26/finvizfinance/pull/94/commits/8740b8323f50650082c80a78ba9f7203be2b9cdb) does not provide the company name.

Suggestion:

Add the following code between lines 137 and 139 of finvizfinance/quote.py

       quote_header = self.soup.find("div", class_="quote-header")
        quote_header_left = quote_header.find("div", class_="quote-header_left")
        quote_header_ticker_wrapper = quote_header_left.find("div", class_="quote-header_ticker-wrapper")
        quote_header_ticker_wrapper_company = quote_header_ticker_wrapper.find("h2")
        if quote_header_ticker_wrapper_company.find("a") != None:
            company_name = quote_header_ticker_wrapper_company.find("a")
        else:
            company_name = quote_header_ticker_wrapper_company
        fundament_info["Company"] = str.strip(company_name.text)

[quote.zip](https://github.com/lit26/finvizfinance/files/12906642/quote.zip)

**Comment by Bozmo** [comment]
Updated finvizfinance 0.14.7rc2 AND beatufifulsoup4 4.12.2 

Screener works for me now.

**Comment by Ponny035** [comment]
Subject: Variable Name Change from `fundament_info["Sector"]` to `fundament_info["Section"]` in [finvizfinance/quote.py](https://github.com/lit26/finvizfinance/pull/94#diff-3da4152a4b26eabf56569374f6be50164c685ed01ccc8003429a19345658e5a6)

Review:

Hey there @lit26 ,

I just noticed the change from `fundament_info["Sector"]` to `fundament_info["Section"] ` in the code. I'm curious about the reason behind this tweak. Is there a specific reason for this change?

1. Clarity and Consistency:

While "Section" seems to convey a similar idea as "Sector" it might confuse people who are used to the old naming. Can you share why you made the change and whether it enhances clarity?

2. Comments and Documentation:

Adding a brief note in the code or updating the documentation could be a helpful addition. When there's a public release, it will help everyone understand what's going on and why.

3. Impact on Other Code:

Perhaps, you could review the codebase to ensure that this variable name change doesn't have unintended consequences or break any existing functionality or code that relies on `fundament_info["Sector"]`.

4. Naming Conventions:

Does this project follow a specific naming convention or style guide? If so, does this change align with it? Consistency in naming is crucial for maintaining a clean and easy-to-work-on codebase.

5. Communication:

Sharing your thoughts on changes like these with the other contributors can help prevent confusion and ensure everyone is on the same page.

I totally understand that we all have different preferences when it comes to coding. I'm just looking to understand the reasoning behind the change and make sure it doesn't cause any hiccups. However, discussing these changes openly can help improve the project for everyone.

Looking forward to hearing your thoughts on this! Thanks for your work on the project.

Cheers, 
@Ponny035

**Comment by lit26** [comment]
I think this is changed by mistake. Will fix it.

**Pull request merged**
