### PR TITLE
Add extra columns for custom screener

### LINKED ISSUE #86: ENH: Extra Columns Available for Custom Table
Some columns are not available in the 'Custom' table.
[finvizfinance provides columns 0 to 70](https://github.com/lit26/finvizfinance/blob/master/finvizfinance/screener/custom.py)

But finviz has a few more columns: 
https://finviz.com/screener.ashx?v=152&c=73,%2075,%2076,%2077,%2078,%2079,%2080,%2081,%2082,%2083,%2084,%2085,%2086,%2087,%2088

```
non_implemented_col_ids = [73, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]

EXTRA_COLUMNS = {
 73 : 'Book Value per Share',
 75 : 'Dividend',
 76 : 'Employees',
 ...
 86 : 'Open'
 87 : 'High',
 88 : 'Low',
}
```

For the sake of cleanness, completeness and because this is an easy fix,
I was going to fiddle with the base code.
But after seeing that the Sept 28 issue got fixed very quickly (big up @lit26 !), it may be better to implement this properly in the original code?

Any chance to see this implemented soon?

### PR DESCRIPTION
**Pull request by lit26**
## Description

Fix #86 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code styling or code optimize

### CODE REVIEW

**Comment by ljilekor** [comment]
There is still an issue

The new columns where not added to NUMBER_COL in util.py

**Comment by lit26** [comment]
Oh, I will take a look.

**Comment by ljilekor** [comment]
And I suspect something is wrong with the 'Dividend' column.
Or should I say, columnS

There seems to be 2.
The initial dataframe created in the screener_view() from Custom.py 
contains 'Dividends' twice!
 image

But once we're in the _get_table() overview.py , the second 'Dividends', one of the new columns, is not there.

- I pumped the resulting 'frame' in a 'new_df' DataFrame for convenience...
`new_df = pd.DataFrame(frame)
image
 
Causing the 
`return pd.concat([df, pd.DataFrame(frame)], ignore_index=True)`
to FAIL (different cols)

**Comment by ljilekor** [comment]
This is caused by the 'info_dict' key getting overwritten (instead of added)

in screener/overview.py in the _get_table() function

`        frame = []
        for row in rows:
            cols = row.findAll("td")[1:]
            info_dict = {}
            for i, col in enumerate(cols):
                # check if the col is number
                if i not in num_col_index:
                    info_dict[table_header[i]] = col.text
                else:
                    info_dict[table_header[i]] = number_covert(col.text)
            frame.append(info_dict)`
            
 table_header[i] is 'Dividend' twice. So the 'Dividend' key is overwritten...
 
 Quite an annoying bug to fix.
 The quick and simple way would be 
 - to rename the 2nd 'Dividend' to 'Dividend Yield' in the COLUMNS of custom.py
 - to handle  `table_header[i]=='Dividend'` as a special case.

but this is just a suggestion.
Maybe there are other implications...

**Comment by lit26** [comment]
Will be fixed in #91

**Pull request merged**
