### PR TITLE
Sourcery refactored code

### PR DESCRIPTION
**Pull request by the-praxs**
## Description

Sourcery refactored code to reflect modern coding practices.

## Type of change

- [x] Code styling or code optimize

## What you did

* Modified string formatting to f-strings
* Added dict comprehension
* Replaced inline variables

### CODE REVIEW

**Comment by lit26** [comment]
I think f-strings only support in Python 3.6 or later

**Comment by the-praxs** [comment]
That is correct. Should I then remove that part of the refactoring?

**Comment by lit26** [comment]
> That is correct. Should I then remove that part of the refactoring?

I think so.

**Comment by lit26** [comment]
Resolve conflict also

**Comment by the-praxs** [comment]
> Resolve conflict also

Done. Please merge.

**Comment by lit26** [comment]
There is another issue. Please check.

**Comment by the-praxs** [comment]
@lit26 Can you merge this and close the PR?

**Comment by lit26** [comment]
https://github.com/lit26/finvizfinance/pull/69/files#r1189156258. You still need to solve this.

**Pull request closed without merging**
